/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vista.Frames;

/**
 *
 * @author maxtr
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        TxtPassword = new javax.swing.JTextField();
        TxtUsuario = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JToggleButton();
        LABELINICIO = new javax.swing.JLabel();
        LABELLOGIN = new javax.swing.JLabel();
        LETRASINGRESAR = new javax.swing.JLabel();
        BOTONLEERMAS = new javax.swing.JButton();
        PNGLOGIN = new javax.swing.JLabel();
        FONDOLETRASBIENVENIDA = new javax.swing.JLabel();
        FONDOLOGIN = new javax.swing.JLabel();
        MENULOGIN = new javax.swing.JMenuBar();
        MENUACERCADE = new javax.swing.JMenu();
        MENUSERVICIOS = new javax.swing.JMenu();
        MENUNOTICIAS = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtPassword.setFont(new java.awt.Font("Mukta Mahee", 0, 24)); // NOI18N
        TxtPassword.setForeground(new java.awt.Color(153, 153, 153));
        TxtPassword.setText("Contraseña");
        TxtPassword.setBorder(null);
        TxtPassword.setFocusTraversalPolicyProvider(true);
        TxtPassword.setName("Contraseña"); // NOI18N
        TxtPassword.setSelectedTextColor(new java.awt.Color(21, 41, 103));
        TxtPassword.setSelectionColor(new java.awt.Color(255, 204, 204));
        TxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 380, 50));

        TxtUsuario.setFont(new java.awt.Font("Mukta Mahee", 0, 24)); // NOI18N
        TxtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        TxtUsuario.setText("Usuario");
        TxtUsuario.setToolTipText("Usuario");
        TxtUsuario.setActionCommand("<Not Set>");
        TxtUsuario.setBorder(null);
        TxtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtUsuario.setMixingCutoutShape(null);
        TxtUsuario.setName("Usuario"); // NOI18N
        TxtUsuario.setOpaque(true);
        TxtUsuario.setSelectedTextColor(new java.awt.Color(21, 41, 103));
        TxtUsuario.setSelectionColor(new java.awt.Color(255, 204, 204));
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 380, 40));
        TxtUsuario.getAccessibleContext().setAccessibleName("Usuario");
        TxtUsuario.getAccessibleContext().setAccessibleDescription("Usuario");

        BtnIngresar.setFont(new java.awt.Font("Mukta Mahee", 1, 45)); // NOI18N
        BtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnIngresar.setText("ENTRAR");
        BtnIngresar.setBorderPainted(false);
        BtnIngresar.setContentAreaFilled(false);
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 410, 60));

        LABELINICIO.setFont(new java.awt.Font("Mukta Mahee", 0, 24)); // NOI18N
        LABELINICIO.setForeground(new java.awt.Color(255, 255, 255));
        LABELINICIO.setText("Inicio");
        getContentPane().add(LABELINICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 60, -1));

        LABELLOGIN.setBackground(new java.awt.Color(21, 41, 103));
        LABELLOGIN.setFont(new java.awt.Font("Mukta Mahee", 1, 48)); // NOI18N
        LABELLOGIN.setForeground(new java.awt.Color(21, 41, 103));
        LABELLOGIN.setText("INGRESAR");
        getContentPane().add(LABELLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 220, -1));

        LETRASINGRESAR.setBackground(new java.awt.Color(255, 255, 255));
        LETRASINGRESAR.setFont(new java.awt.Font("Mukta Mahee", 1, 24)); // NOI18N
        LETRASINGRESAR.setForeground(new java.awt.Color(21, 41, 103));
        LETRASINGRESAR.setText("Por favor ingrese su usuario y contraseña");
        getContentPane().add(LETRASINGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 440, 50));

        BOTONLEERMAS.setBorderPainted(false);
        BOTONLEERMAS.setContentAreaFilled(false);
        BOTONLEERMAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONLEERMASActionPerformed(evt);
            }
        });
        getContentPane().add(BOTONLEERMAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 160, 40));
        BOTONLEERMAS.getAccessibleContext().setAccessibleName("");

        PNGLOGIN.setIcon(new javax.swing.ImageIcon("/Users/mariagutierrezgonzalez/Documents/GitHub/EDD1_LAB1/src/main/java/com/mycompany/vista/imagenes/SINFONDOPARTELOGIN.png")); // NOI18N
        getContentPane().add(PNGLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1280, 800));

        FONDOLETRASBIENVENIDA.setIcon(new javax.swing.ImageIcon("/Users/mariagutierrezgonzalez/Documents/GitHub/EDD1_LAB1/src/main/java/com/mycompany/vista/imagenes/SINFONDOLETRASDEBIENVENIDA.png")); // NOI18N
        FONDOLETRASBIENVENIDA.setText("jLabel2");
        getContentPane().add(FONDOLETRASBIENVENIDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));
        FONDOLETRASBIENVENIDA.getAccessibleContext().setAccessibleName("");

        FONDOLOGIN.setIcon(new javax.swing.ImageIcon("/Users/mariagutierrezgonzalez/Documents/GitHub/EDD1_LAB1/src/main/java/com/mycompany/vista/imagenes/FONDOLOGIN-2.png")); // NOI18N
        getContentPane().add(FONDOLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MENULOGIN.setForeground(new java.awt.Color(21, 41, 103));

        MENUACERCADE.setForeground(new java.awt.Color(21, 41, 103));
        MENUACERCADE.setText("Acerca de ");
        MENUACERCADE.setFont(new java.awt.Font("Mukta Mahee", 1, 15)); // NOI18N
        MENULOGIN.add(MENUACERCADE);

        MENUSERVICIOS.setForeground(new java.awt.Color(21, 41, 103));
        MENUSERVICIOS.setText("Servicios");
        MENUSERVICIOS.setFont(new java.awt.Font("Mukta Mahee", 1, 15)); // NOI18N
        MENULOGIN.add(MENUSERVICIOS);

        MENUNOTICIAS.setForeground(new java.awt.Color(21, 41, 103));
        MENUNOTICIAS.setFont(new java.awt.Font("Mukta Mahee", 1, 15)); // NOI18N
        MENUNOTICIAS.setLabel("Noticias/Artículos");
        MENULOGIN.add(MENUNOTICIAS);

        setJMenuBar(MENULOGIN);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        String usuario = TxtUsuario.getText();
        String contrasena = TxtPassword.getText();

        if (usuario.equals("admin") && contrasena.equals("admin")) {

            this.dispose();

            new MenuFrame().setVisible(true);
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void BOTONLEERMASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONLEERMASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTONLEERMASActionPerformed

    private void TxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONLEERMAS;
    private javax.swing.JToggleButton BtnIngresar;
    private javax.swing.JLabel FONDOLETRASBIENVENIDA;
    private javax.swing.JLabel FONDOLOGIN;
    private javax.swing.JLabel LABELINICIO;
    private javax.swing.JLabel LABELLOGIN;
    private javax.swing.JLabel LETRASINGRESAR;
    private javax.swing.JMenu MENUACERCADE;
    private javax.swing.JMenuBar MENULOGIN;
    private javax.swing.JMenu MENUNOTICIAS;
    private javax.swing.JMenu MENUSERVICIOS;
    private javax.swing.JLabel PNGLOGIN;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
