/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vista.Frames;

/**
 *
 * @author Juan
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BOTONCITAS = new javax.swing.JButton();
        BOTONMEDICOS = new javax.swing.JButton();
        FONDOBOTONES = new javax.swing.JLabel();
        FONDOMENU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        BOTONCITAS.setFont(new java.awt.Font("Mukta Mahee", 1, 80)); // NOI18N
        BOTONCITAS.setForeground(new java.awt.Color(255, 255, 255));
        BOTONCITAS.setToolTipText("");
        BOTONCITAS.setBorderPainted(false);
        BOTONCITAS.setContentAreaFilled(false);
        BOTONCITAS.setLabel("Citas");
        BOTONCITAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONCITASActionPerformed(evt);
            }
        });
        getContentPane().add(BOTONCITAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 360, 120));

        BOTONMEDICOS.setFont(new java.awt.Font("Mukta Mahee", 1, 80)); // NOI18N
        BOTONMEDICOS.setForeground(new java.awt.Color(255, 255, 255));
        BOTONMEDICOS.setToolTipText("");
        BOTONMEDICOS.setBorderPainted(false);
        BOTONMEDICOS.setContentAreaFilled(false);
        BOTONMEDICOS.setLabel("Médicos");
        BOTONMEDICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONMEDICOSActionPerformed(evt);
            }
        });
        getContentPane().add(BOTONMEDICOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 360, 120));

        FONDOBOTONES.setMaximumSize(new java.awt.Dimension(1280, 800));
        FONDOBOTONES.setMinimumSize(new java.awt.Dimension(1280, 800));
        getContentPane().add(FONDOBOTONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));
        getContentPane().add(FONDOMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -2, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONCITASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONCITASActionPerformed
      new RegistrarPacientesFrame().setVisible(true);
    }//GEN-LAST:event_BOTONCITASActionPerformed

    private void BOTONMEDICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONMEDICOSActionPerformed
        new RegistrarMedicosFrame().setVisible(true);
    }//GEN-LAST:event_BOTONMEDICOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONCITAS;
    private javax.swing.JButton BOTONMEDICOS;
    private javax.swing.JLabel FONDOBOTONES;
    private javax.swing.JLabel FONDOMENU;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
