/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vista;

/**
 *
 * @author maxtr
 */
public class Main extends javax.swing.JFrame {

    Pacientes pacientes = new Pacientes();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BOTONCMEDICOS = new javax.swing.JButton();
        BOTONCITAS = new javax.swing.JButton();
        FONDOBOTONESYLETRA = new javax.swing.JLabel();
        FONDOPRINCIPALMAIN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BOTONCMEDICOS.setFont(new java.awt.Font("Verdana", 1, 60)); // NOI18N
        BOTONCMEDICOS.setForeground(new java.awt.Color(255, 255, 255));
        BOTONCMEDICOS.setText("MÉDICOS");
        BOTONCMEDICOS.setContentAreaFilled(false);
        BOTONCMEDICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONCMEDICOSActionPerformed(evt);
            }
        });
        getContentPane().add(BOTONCMEDICOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 370, 120));

        BOTONCITAS.setFont(new java.awt.Font("Verdana", 1, 75)); // NOI18N
        BOTONCITAS.setForeground(new java.awt.Color(255, 255, 255));
        BOTONCITAS.setText("CITAS");
        BOTONCITAS.setContentAreaFilled(false);
        BOTONCITAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONCITASActionPerformed(evt);
            }
        });
        getContentPane().add(BOTONCITAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 370, 120));
        BOTONCITAS.getAccessibleContext().setAccessibleName("BOTONCITAS");

        FONDOBOTONESYLETRA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/vista/imagenes/MEDBOOK BOTONES MAIN SIN FONDO.png"))); // NOI18N
        getContentPane().add(FONDOBOTONESYLETRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        FONDOPRINCIPALMAIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/vista/imagenes/MAIN FONDO_SOLO FOTO.png"))); // NOI18N
        getContentPane().add(FONDOPRINCIPALMAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONCITASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONCITASActionPerformed
        new RegistrarPacientesFrame().setVisible(true);
    }//GEN-LAST:event_BOTONCITASActionPerformed

    private void BOTONCMEDICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONCMEDICOSActionPerformed
        new RegistrarMedicosFrame().setVisible(true);
    }//GEN-LAST:event_BOTONCMEDICOSActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONCITAS;
    private javax.swing.JButton BOTONCMEDICOS;
    private javax.swing.JLabel FONDOBOTONESYLETRA;
    private javax.swing.JLabel FONDOPRINCIPALMAIN;
    // End of variables declaration//GEN-END:variables
}
